/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/henrik-wool-rug-160x230cm-mustard-and-grey-51f035b3295145a5ad5dab958edcd4d2
Title: Henrik Wool Rug 160x230cm, Mustard and Grey
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane001_FLOOR_0: THREE.Mesh;
    Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HENRIK_LARGE_WOOL_RUG_0: THREE.Mesh;
  };
  materials: {
    FLOOR: THREE.MeshStandardMaterial;
    HENRIK_LARGE_WOOL_RUG: THREE.MeshStandardMaterial;
  };
};

export function Rug(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./models/rug.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_FLOOR_0.geometry}
        material={materials.FLOOR}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Henrik_Hand_Tufted_Wool_Rug_Grey_and_RedMulti_120x180cm_HENRIK_LARGE_WOOL_RUG_0
            .geometry
        }
        material={materials.HENRIK_LARGE_WOOL_RUG}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/rug.glb");
